using RailwayWebBuilderCore.Data;

namespace RailwayWebBuilderCore._SiteData.ModelRailways.Layouts
{
    internal class WelbyLane : LayoutBase
    {
        public WelbyLane()
        {
            Name = LayoutNamesEnums.WelbyLane;
            Owner = "Mark Pearson";
            Description = "WELBY LANE R.T.C\r\nTRACTION AND ROLLING STOCK MAINTENANCE DEPOT\r\n\r\nPRESENTED BY MARK PEARSON - MEMBER OF SDEG\r\n\r\nWith the continuing development in the 1970s of the Railway Technical Centre at Derby it\r\nwas decided that minor repairs and servicing could be managed at the site of the Test track\r\nwithout the need for a return to Derby or Toton.\r\n\r\nWelby Lane lies just off the Old Dalby test track at the Asfordby end, in fact, the spur still\r\nexists into the Asfordby Business Park, originally part of the Great Northern Line north and\r\nseveral quarries in the area. The R.T.C decided that the spur provided an excellent area to\r\nbuild a maintenance facility and with the nearby quarry reception sidings gained additional\r\nstorage space whilst still giving access to the main test track and main line.\r\n\r\nThe scale is OO, using fine-scale and peco code 75 track and points. In fact, the layout was\r\nbuilt in two halves and then also an extension was added sometime later! The original shed area\r\nis much older and was built as a small test bed for DCC and code 75 track, The newer 'ex\r\nreception sidings area' was built some years after with the scrapyard extension being recently\r\nbuilt. The overall length is now just over 20 feet in length by 2 feet wide maximum. Control\r\nis by Lenz DCC, using an express net to enable more than one operator to use the layout. Slow\r\naction point motors are Cobolt, Traintronics, or Fulgrex. Lights and accessories are from\r\nvarious propriety suppliers and sources.\r\n\r\nAll the locomotives are sound-fitted fitted giving an extra dimension, especially to some of the odd\r\nclasses of diesels that sadly are no longer around, Due to the diversity of the R.T.C constantly\r\nexperimenting and developing, some items of stock seen on Welby Lane may only be correct\r\nfor 'that one day in time', and due to the secrecy and lack of photographic evidence of\r\ncertain prototypes, some items have had to be modeled as such from what we can see/\r\nknow.\r\n\r\nSome of the buildings on the layout are based on actual structures on the Mickleover and Old\r\nDalby test tracks - even down to the guard dog compound at Mickleover. The office block\r\nand A.P.T testing house are inspired by the structures at Old Dalby,and have been either\r\n\r\nscratch built or by modifying kits to suit."; // TODO Needs description
        }
    }
}